"""add properties column to jobs table

Revision ID: 33f08f2148bc
Revises: 0aaeac238e24
Create Date: 2025-03-19 18:00:01.479437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f08f2148bc'
down_revision: Union[str, None] = '0aaeac238e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'properties')
    # ### end Alembic commands ###
