"""add properties column to jobs table

Revision ID: 47e38c0dc4f5
Revises: 33f08f2148bc
Create Date: 2025-03-19 18:04:29.541210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e38c0dc4f5'
down_revision: Union[str, None] = '33f08f2148bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
