"""description

Revision ID: 49b144b6349e
Revises: f9c8178c6721
Create Date: 2025-03-20 23:26:17.094469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b144b6349e'
down_revision: Union[str, None] = 'f9c8178c6721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.drop_constraint('interviews_application_id_fkey', 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_column('interviews', 'application_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_application_id_fkey', 'interviews', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_column('interviews', 'candidate_id')
    # ### end Alembic commands ###
