"""add assessment_score and resume_score to candidates table

Revision ID: 4e6c4e215354
Revises: 47e38c0dc4f5
Create Date: 2025-03-19 19:22:05.814322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6c4e215354'
down_revision: Union[str, None] = '47e38c0dc4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('assessment_score', sa.Float(), nullable=True))
    op.add_column('candidates', sa.Column('resume_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_score')
    op.drop_column('candidates', 'assessment_score')
    # ### end Alembic commands ###
