"""update_company_model

Revision ID: 642fe0ffabe1
Revises: 
Create Date: 2025-03-21 12:56:12.210371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642fe0ffabe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('smart_hire_enabled', sa.Boolean(), nullable=True))
    op.drop_constraint('leads_email_key', 'leads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('leads_email_key', 'leads', ['email'])
    op.drop_column('jobs', 'smart_hire_enabled')
    # ### end Alembic commands ###
