"""add_company_id_to_candidates

Revision ID: 995614e91fdd
Revises: 4a0b1300d8ce
Create Date: 2025-03-21 20:33:00.130391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995614e91fdd'
down_revision: Union[str, None] = '4a0b1300d8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_lead_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('jobs_lead_id_fkey', 'jobs', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###
