"""description

Revision ID: bc5a3b75a299
Revises: 
Create Date: 2025-03-21 18:38:18.892997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5a3b75a299'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'lead_id')
    # ### end Alembic commands ###
