"""description

Revision ID: cf2a9c85ab7b
Revises: 4fd742474dbe
Create Date: 2025-03-19 22:06:13.549738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2a9c85ab7b'
down_revision: Union[str, None] = '4fd742474dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('resume_s3_url', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'candidates', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'resume_s3_url')
    op.drop_column('candidates', 'job_id')
    # ### end Alembic commands ###
