"""update_job_model

Revision ID: ed2857652f8f
Revises: d651b42cfce2
Create Date: 2025-03-20 10:36:32.254674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2857652f8f'
down_revision: Union[str, None] = 'd651b42cfce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jobs', sa.Column('properties', sa.JSON(), nullable=True))
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'properties')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'job_description')
    # ### end Alembic commands ###
